// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBLj26YxZzde91mAi_cbLVooW5cl0bPhqk',
    appId: '1:510990442677:web:92191aada03bdc00ac9efc',
    messagingSenderId: '510990442677',
    projectId: 'trial-1-dream-team',
    authDomain: 'trial-1-dream-team.firebaseapp.com',
    storageBucket: 'trial-1-dream-team.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC0QygEi9FkwFb0g2hGxEm9NZjefnGPOGo',
    appId: '1:510990442677:android:5ebfffe6dc0842dcac9efc',
    messagingSenderId: '510990442677',
    projectId: 'trial-1-dream-team',
    storageBucket: 'trial-1-dream-team.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBFCbVknoyflbWhUUJ6P5pCKsPr8l0ahNY',
    appId: '1:510990442677:ios:892ec2a8e6bb85e9ac9efc',
    messagingSenderId: '510990442677',
    projectId: 'trial-1-dream-team',
    storageBucket: 'trial-1-dream-team.appspot.com',
    iosBundleId: 'com.example.sarakel',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBFCbVknoyflbWhUUJ6P5pCKsPr8l0ahNY',
    appId: '1:510990442677:ios:4f3c91ad50803bc7ac9efc',
    messagingSenderId: '510990442677',
    projectId: 'trial-1-dream-team',
    storageBucket: 'trial-1-dream-team.appspot.com',
    iosBundleId: 'com.example.sarakel.RunnerTests',
  );
}
